More helpers, removing unused brew stuff

diff --git a/.config/yadm/scripts/ecr-docker-login b/.config/yadm/scripts/ecr-docker-login
--- a/.config/yadm/scripts/ecr-docker-login
+++ b/.config/yadm/scripts/ecr-docker-login
@@ -3,56 +3,47 @@
 SCRIPT_NAME=${0##*/}
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
-log_info() {
-  echo "[\033[0;34mINFO\033[0m] ${1}"
-}
-
-log_error() {
-  echo "[\033[0;31mERROR\033[0m] ${1}"
-}
-
-log_verbose() {
-  if [[ ${VERBOSE_LOGGING:-1} -eq 0 ]]; then
-    echo "[\033[0;32mDEBUG\033[0m] ${1}"
-  fi
-}
+if [ -f "${HOME}/.logging" ]; then
+  source "${HOME}/.logging"
+fi
 
 usage() {
-  echo "Usage: ${SCRIPT_NAME} --account 1234567890 --region us-east-1"
-  echo ""
-  echo " -a --account  The account to login to. Defaults to the environment variables AWS_PROFILE or AWS_DEFAULT_PROFILE."
-  echo " -r --region   The region to login to. Defaults to us-east-1."
+cat << USAGE
+  Usage: ${SCRIPT_NAME} --account 1234567890 --region us-east-1
+  
+   -a --account  The account to login to. Defaults to the environment variables AWS_PROFILE or AWS_DEFAULT_PROFILE.
+   -r --region   The region to login to. Defaults to us-east-1.
+USAGE
 }
 
 account="${AWS_PROFILE:-${AWS_DEFAULT_PROFILE}}"
 account="${account#awsaml-}"
 region="us-east-1"
 
-SHORTOPTS="a:r:h"
-LONGOPTS="account:,region:,help"
+OPTS="a:r:h"
 REQUIREDOPTS=("account" "region")
-if ! options=$(getopt -n "${SCRIPT_NAME}" -o "${SHORTOPTS}" -l "${LONGOPTS}" -- "$@"); then
-  log_error "Unable to set cli options"
-  exit 1
-fi
 
-eval set -- "${options}"
-while [ $# -gt 0 ]; do
-  case "$1" in
-    -a|--account) shift; account="${1}" ;;
-    -r|--region) shift; region="${1}" ;;
-    -h|--help) usage; exit 0 ;;
-    --) shift; break ;;
-    *) break ;;
+while getopts "${OPTS}" opt; do
+  case "${opt}" in
+    a) account="${OPTARG}" ;;
+    r) region="${OPTARG}" ;;
+    h) usage
+       exit 0
+       ;;
+    *)
+     log_error "Invalid Option: -${opt} ${OPTARG}"
+     usage
+     exit 1
+     ;;
   esac
   shift
 done
+shift $((OPTIND -1))
 
 # Validation...
 for required in "${REQUIREDOPTS[@]}"; do
-  log_verbose "Checking required parameter '${required}' is set..."
   if [[ -z "${!required}" ]]; then
-    log_error "Required parameter missing [${required}]"
+    log_error "Required parameter missing"
     usage
     exit 1
   fi
@@ -60,17 +51,19 @@ done
 
 log_info "Attempting to login to ECR in account ${account} - ${region}"
 
-additional_args=""
-docker_version=$(docker version -f "{{.Server.Version}}" | cut -d . -f 1,2)
+docker_version=$(docker version -f "{{.Server.Version}}")
+log_info " > Docker ${docker_version} detected"
 if [ ! "$(printf '%s\n' "17.06" "${docker_version}" | sort -V | head -n1)" = "17.06" ]; then
   additional_args="--no-include-email"
 fi
 # Workaround incase someone has installed 2.* of the aws-cli
 aws_cli_version="$(echo "$(aws --version)" | cut -d ' ' -f 1 | cut -d / -f 2 | cut -d . -f 1)"
+log_info " > Using V${aws_cli_version} of aws-cli to login to ECR"
 if [ "${aws_cli_version}" -lt "2" ]; then
-  eval "$(aws ecr get-login --registry-ids ${account} --region ${region} ${additional_args})"
+  $(AWS_PROFILE=awsaml-${account} aws ecr get-login --registry-ids ${account} --region ${region} ${additional_args} 2>&1 >/dev/null)
 else
-  docker login -u AWS -p "$(aws ecr get-login-password --region ${region} ${additional_args})" "https://${account}.dkr.ecr.${region}.amazonaws.com"
+  echo "$(AWS_PROFILE=awsaml-${account} aws ecr get-login-password --region ${region} ${additional_args})" | \
+    docker login -u AWS --password-stdin "https://${account}.dkr.ecr.${region}.amazonaws.com" 2>&1 >/dev/null
 fi
 
 exit 0
diff --git a/.config/yadm/scripts/kms-helper b/.config/yadm/scripts/kms-helper
--- a/.config/yadm/scripts/kms-helper
+++ b/.config/yadm/scripts/kms-helper
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+if [ -f "${HOME}/.logging" ]; then
+  source "${HOME}/.logging"
+fi
+
 SCRIPT_NAME=${0##*/}
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
@@ -15,17 +19,17 @@ cat << USAGE
   
   ${VALID_COMMANDS_STR}
     The action to perform.
-  -k --key-alias        
+  -k         
     The KMS key to use when encrypting a value.
-  -r --region           ${DEFAULT_REGION}
+  -r  ${DEFAULT_REGION}
     Region where the KMS key lives.
-  -t --text
+  -t 
     The value to encrypt or decrypt.
 
   ${SCRIPT_NAME} encrypt -k terraform-secrets-product-prod-1 -t "secret_password"
   ${SCRIPT_NAME} decrypt -t "AQICAHgAo5v8YsJZTNHqa6WtDuiMFzVkKYglrpVUghT0JiDwSgHH2u ..."
-  ${SCRIPT_NAME} encrypt --region eu-central-1 -k terraform-secrets-product-prod-0 -t "secret_password"
-  ${SCRIPT_NAME} decrypt --region eu-central-1 -t "AQICAHgAo5v8YsJZTNHqa6WtDuiMFzVkKYglrpVUghT0JiDwSgHH2u ..."
+  ${SCRIPT_NAME} encrypt -r eu-central-1 -k terraform-secrets-product-prod-0 -t "secret_password"
+  ${SCRIPT_NAME} decrypt -r eu-central-1 -t "AQICAHgAo5v8YsJZTNHqa6WtDuiMFzVkKYglrpVUghT0JiDwSgHH2u ..."
 USAGE
 }
 
@@ -58,35 +62,37 @@ decrypt() {
   echo "$(echo "${decrypted}" | base64 -D)"
 }
 
-SHORTOPTS="r:k:t:h"
-LONGOPTS="region:,key-alias:,text:,help"
-REQUIREDOPTS=("region" "key_alias" "text")
-ARGS=$(getopt -s bash --options "${SHORTOPTS}" --longoptions "${LONGOPTS}" --name "${SCRIPT_NAME}" -- "$@" )
-
 region="${DEFAULT_REGION}"
 key_alias=""
 text=""
 
-eval set -- "${ARGS}"
-while true; do
-  case $1 in
-    -k|--key-alias) shift; key_alias="${1}" ;;
-    -r|--region) shift; region="${1}" ;;
-    -t|--text) shift; text="${1}" ;;
-    -h|--help) usage; exit 0 ;;
-    --) shift; break ;;
-    *) shift; break ;;
-  esac
-  shift
-done
+OPTS="r:k:t:h"
+REQUIREDOPTS=("region" "key_alias" "text")
 
-command="${1}"
+command="${1}"; shift
 if ! [[ "${command}" =~ ^(${VALID_COMMANDS_STR})$ ]]; 
 then 
-  echo "Must be one of ${VALID_COMMANDS_STR}"
+  echo "Command [${command}] must be one of ${VALID_COMMANDS_STR}"
   usage
   exit 1
 fi
+
+while getopts "${OPTS}" opt; do
+  case "${opt}" in
+    k) key_alias="${OPTARG}" ;;
+    r) region="${OPTARG}" ;;
+    t) text="${OPTARG}" ;;
+    h) usage
+       exit 0
+       ;;
+    *)
+     log_error "Invalid Option: -${opt} ${OPTARG}"
+     usage
+     exit 1
+     ;;
+  esac
+done
+shift $((OPTIND -1))
 
 case ${command} in
   encrypt)
diff --git a/.config/yadm/scripts/port-forwarder b/.config/yadm/scripts/port-forwarder
--- a/.config/yadm/scripts/port-forwarder
+++ b/.config/yadm/scripts/port-forwarder
@@ -1,37 +1,34 @@
 #!/usr/bin/env sh
 
+set -e
+
 SCRIPT_NAME=${0##*/}
 
-if [ -e ${HOME}/.logging ]; then
-  source ${HOME}/.logging
-else
-  function log_info () {
-    echo "[INFO] \033[0;32m${1}\033[0m"
-  }
-  function log_error () {
-    echo "[ERROR] \033[0;31m${1}\033[0m"
-  }
+if [ -f "${HOME}/.logging" ]; then
+  source "${HOME}/.logging"
 fi
 
-function usage () {
-  echo "Usage: ${SCRIPT_NAME} -q <query> -p <port> -n <namespace> [-k <kube_config>] [-r]"
-  echo "   -q --query       The pattern to match pods with."
-  echo "   -p --port        The port to forward."
-  echo "   -n --namespace   The namespace to search for pods."
-  echo "                    Defaults to 'default'."
-  echo " Optional:"
-  echo "   -k --kube-config The kubeconfig to use, if different than the current one."
-  echo "                    Defaults to the value of 'KUBECONFIG'."
-  echo "   -r --random-port Whether to use random ports. If false, will attempt to use"
-  echo "                    the port to forward + 1 e.g."
-  echo "                    pod-1 -> 8080:8080"
-  echo "                    pod-2 -> 8080:8081"
-  echo "                    pod-3 -> 8080:8082"
-  echo ""
-  echo " Examples:"
-  echo "  ${SCRIPT_NAME} -q apiservice -p 8080"
-  echo "  ${SCRIPT_NAME} -q fluentd -n logging -p 24231 -k ~/.kube/pd-test-1.kubeconfig -r"
-  echo "  KUBECONFIG=\"~/.kube/pd-test-1.kubeconfig\" ${SCRIPT_NAME} -q fluentd -n logging -p 24231"
+usage () {
+cat << USAGE  
+  Usage: ${SCRIPT_NAME} [-q <query>] [-p <port>] [-n <namespace>] [-k <kube_config>] [-r]
+
+  Options
+  Required:
+    -q  The pattern to match pods with.
+    -p  The port to forward.
+    -n  The namespace to search for pods. Defaults to 'default'.
+   Optional:
+    -k  The kubeconfig to use, if different than the current one. Defaults to the value of 'KUBECONFIG'.
+    -r  Whether to use random ports. If false, will attempt to use the port to forward + 1 e.g.
+        pod-1 -> 8080:8080
+        pod-2 -> 8081:8080
+        pod-3 -> 8082:8080
+  
+   Examples:
+    ${SCRIPT_NAME} -q apiservice -p 8080
+    ${SCRIPT_NAME} -q fluentd -n logging -p 24231 -k ~/.kube/pd-test-1.kubeconfig -r
+    KUBECONFIG=\"~/.kube/pd-test-1.kubeconfig\" ${SCRIPT_NAME} -q fluentd -n logging -p 24231
+USAGE  
 }
 
 query=""
@@ -40,32 +37,31 @@ kube_config=${KUBECONFIG}
 namespace="default"
 use_random_port=false
 
-SHORTOPTS="q:p:n:k:rh"
-LONGOPTS="query:,port:,namespace:,kube-config:,random-port,help"
-REQUIREDOPTS=("query port kube_config")
-if ! options=$(getopt -n "${SCRIPT_NAME}" -o "${SHORTOPTS}" -l "${LONGOPTS}" -- "$@"); then
-  log_error "Unable to set cli options"
-  exit 1
-fi
+OPTS="q:p:n:k:rh"
+REQUIREDOPTS=("query" "port" "kube_config" "namespace")
 
-eval set -- "${options}"
-while [ $# -gt 0 ]; do
-  case "$1" in
-    -q|--query) shift; query="${1}" ;;
-    -p|--port) shift; port="${1}" ;;
-    -n|--namespace) shift; namespace="${1}" ;;
-    -k|--kube-config) shift; kube_config="${1}" ;;
-    -r|--random-port) use_random_port=true ;;
-    -h|--help) usage; exit 0 ;;
-    --) shift; break ;;
-    *) break ;;
+while getopts "${OPTS}" opt; do
+  case "${opt}" in
+    q) query="${OPTARG}" ;;
+    p) port="${OPTARG}" ;;
+    n) namespace="${OPTARG}" ;;
+    k) kube_config="${OPTARG}" ;;
+    r) use_random_port=true ;;
+    h) usage
+       exit 0
+       ;;
+    *)
+     log_error "Invalid Option: -${opt} ${OPTARG}"
+     usage
+     exit 1
+     ;;
   esac
-  shift
 done
+shift $((OPTIND -1))
 
 for required in ${REQUIREDOPTS}; do
   if [[ -z "${!required}" ]]; then
-    log_error "Required parameter missing [${required}]"
+    log_error "Required parameter missing"
     usage
     exit 1
   fi
