Adding more helper scripts

diff --git a/.yadm/scripts/get-kubernetes-secret b/.yadm/scripts/get-kubernetes-secret
--- a/.yadm/scripts/get-kubernetes-secret
+++ b/.yadm/scripts/get-kubernetes-secret
@@ -5,6 +5,19 @@ set -e
 DEFAULT_NAMESPACE="kube-system"
 SCRIPT_NAME=${0##*/}
 
+RED="\033[0;31m"
+WHITE="\033[0m"
+
+function log_info () {
+  timestamp=$(date +"%Y-%m-%d %H-%M-%S")
+  echo "[${timestamp}] ${1}"
+}
+
+function log_error () {
+  timestamp=$(date +"%Y-%m-%d %H-%M-%S")
+  echo "[${timestamp}] ${RED}${1}${WHITE}"
+}
+
 function banner () {
   echo "========================================================================="
 }
@@ -19,10 +32,12 @@ function usage () {
 
 list="0"
 secret=""
+kube_config=${KUBECONFIG}
 namespace=${DEFAULT_NAMESPACE}
 
 SHORTOPTS="s:n:k:lh"
 LONGOPTS="secret:,namespace:,kubeconfig:,list,help"
+REQUIREDOPTS=("kube_config")
 ARGS=$(getopt -s bash --options "${SHORTOPTS}" --longoptions "${LONGOPTS}" --name "${SCRIPT_NAME}" -- "$@" )
 
 eval set -- "${ARGS}"
@@ -38,7 +53,7 @@ while true; do
       ;;
     -k|--kubeconfig)
       shift
-      export KUBECONFIG="${1}"
+      kube_config="${1}"
       ;;
     -l|--list)
       list="1"
@@ -59,25 +74,27 @@ while true; do
   shift
 done
 
-if [[ -z "${namespace}" || -z "${KUBECONFIG}" ]]; then
-  echo "Missing required parameters:"
-  echo "> -n         namespace      [${namespace}]"
-  echo "> -k         kubectl config [${KUBECONFIG}]"
+for required in ${REQUIREDOPTS}; do
+  if [[ -z "${!required}" ]]; then
+    log_error "Required parameter missing [${required}]"
+    usage
+    exit 1
+  fi
+done
+
+if [[ "${list}" == "0" && -z "${secret}" ]]; then
+  log_error "Must specify either list all or a secret to search for"
   usage
   exit 1
 fi
 
-echo "Attempting to retrieve the following from kubernetes using kubectl config [${KUBECONFIG}]:"
-echo "> secret    ${secret}"
-echo "> namespace ${namespace}"
+log_info "Attempting to retrieve the following from kubernetes using kubectl config [${KUBECONFIG}] from namespace [${namespace}]..."
 
-json=$(kubectl get secrets -n ${namespace} -o json)
+json=$(KUBECONFIG=${kube_config} kubectl get secrets -n ${namespace} -o json)
 result=""
 if [[ "${list}" == "1" ]]; then
-    echo "list"
   result=$(echo "${json}" | jq -r '.items[] | select(.metadata.name) | [.metadata.name, .data.token] | @tsv')
 else
-    echo "no list"
   result=$(echo "${json}" | jq -r --arg VAL "${secret}" '.items[] | select(.metadata.name | contains($VAL)) | [.metadata.name, .data.token] | @tsv')
 fi
 
@@ -85,13 +102,13 @@ echo "${result}" | while IFS=$'\t' read -r name token; do
   if [[ ! -z "${token}" ]]; then
     echo
     echo
-    echo "${name}"
+    log_info "${name}"
     banner
     echo "\"$(echo ${token} | base64 --decode)\""
     banner
   fi
 done
 
-echo "Done!"
+log_info "Done!"
 
 exit 0
