Adding more helper scripts

diff --git a/.yadm/scripts/get-kubernetes-secret b/.yadm/scripts/get-kubernetes-secret
--- a/.yadm/scripts/get-kubernetes-secret
+++ b/.yadm/scripts/get-kubernetes-secret
@@ -17,25 +17,21 @@ secret=""
 namespace=${DEFAULT_NAMESPACE}
 while getopts ":hs:n:" o; do
   case "${o}" in
-    s)
-      secret="${OPTARG}"
-      ;;
-    n)
-      namespace="${OPTARG}"
-      ;;
-    h)
-      usage
-      exit 0
-      ;;
-    :) 
-      printf "missing argument for -%s\n" "$OPTARG" >&2
-      echo "$usage" >&2
-      exit 1
-      ;;  
-    *)
-      usage
-      exit 0
-      ;;
+    s)  secret="${OPTARG}"
+        ;;
+    n)  namespace="${OPTARG}"
+        ;;
+    h)  usage
+        exit 0
+        ;;
+    :)  echo "Missing argument for -${OPTARG}"
+        usage
+        exit 1
+        ;;  
+    *)  echo "Unrecognised argument for -${OPTARG}"
+        usage
+        exit 1
+        ;;
   esac
 done
 shift $((OPTIND - 1))
