Fixing helper scripts and fixing PATH (can't set in ~/.zshenv)

diff --git a/.yadm/scripts/get-kubernetes-secret b/.yadm/scripts/get-kubernetes-secret
--- a/.yadm/scripts/get-kubernetes-secret
+++ b/.yadm/scripts/get-kubernetes-secret
@@ -30,53 +30,41 @@ function usage () {
   echo "   -q --quiet       Suppress output"
 }
 
-SHORTOPTS="s:n:k:lhq"
-LONGOPTS="secret:,namespace:,kubeconfig:,list,help,quiet"
-REQUIREDOPTS=("kube_config")
-ARGS=$(getopt -s bash --options "${SHORTOPTS}" --longoptions "${LONGOPTS}" --name "${SCRIPT_NAME}" -- "$@" )
-
 secrets=()
 list=0
 quiet=0
 kube_config=${KUBECONFIG}
 namespace=${DEFAULT_NAMESPACE}
 
-eval set -- "${ARGS}"
-while true; do
-  case $1 in
-    -s|--secret)
-      shift
-      secrets+=("${1}")
-      ;;
-    -n|--namespace)
-      shift
-      namespace="${1}"
-      ;;
-    -k|--kubeconfig)
-      shift
-      kube_config="${1}"
-      ;;
-    -l|--list)
-      list=1
-      ;;
-    -q|--quiet)
-      quiet=1
-      ;;
-    -h|--help)
-      usage
-      exit 0
-      ;;
-    --)
-      shift
-      break
-      ;;
-    *)
-      shift
-      break
-      ;;
+SHORTOPTS="s:n:k:lhq"
+LONGOPTS="secret:,namespace:,kubeconfig:,list,help,quiet"
+REQUIREDOPTS=("kube_config")
+if ! options=$(getopt -n "${SCRIPT_NAME}" -o "${SHORTOPTS}" -l "${LONGOPTS}" -- "$@"); then
+  log_error "Unable to set cli options"
+  exit 1
+fi
+
+eval set -- "${options}"
+while [ $# -gt 0 ]; do
+  case "$1" in
+    -s|--secret) shift; secrets+=("${1}") ;;
+    -n|--namespace) shift; namespace="${1}" ;;
+    -k|--kubeconfig) shift; kube_config="${1}" ;;
+    -l|--list) list=1 ;;
+    -q|--quiet) quiet=1 ;;
+    -h|--help) usage; exit 0 ;;
+    --) shift; break ;;
+    *) break ;;
   esac
   shift
 done
+
+if [[ ${quiet} -eq 0 ]]; then
+  log_info "Using the following option(s):"
+  for o in "list" "quiet" "secrets" "kube_config" "namespace"; do
+    log_info "- ${o}: ${!o}"
+  done
+fi
 
 for required in ${REQUIREDOPTS}; do
   if [[ -z "${!required}" ]]; then
@@ -110,7 +98,7 @@ fi
 for r in "${results[@]}"; do
   echo "${r}" | while IFS=$'\t' read -r name token; do
     if [[ ! -z "${token}" ]]; then
-      if [[ ${quiet} -eq 0 ]]; then
+      if [[ ${list} -eq 1 ]] || [[ ${quiet} -eq 0 ]]; then
         log_info
         log_info "${name}"
         banner
